name: Accessibility Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Run accessibility test
        run: npx playwright test

      - name: Save Axe accessibility report
        uses: actions/upload-artifact@v2
        with:
          name: axe-report
          path: test-results/accessibility-results.json
