name: Lighthouse Report

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm install --global @lhci/cli
      - name: Run Lighthouse
        run: lhci autorun
      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: "./.lighthouseci/created_at/*.html"
