name: W3C Validation Test

on: [push]

jobs:
  w3c-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run W3C validation test
        run: npx html-validate
        env:
          VALIDATOR_OPTIONS: --format=json --file=validation-report.json
      - name: Upload validation report
        uses: actions/upload-artifact@v2
        with:
          name: validation-report
          path: validation-report.json
